env:
  es6: true
  node: true
  mocha: true
extends:
  - 'eslint:recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
